services:
  db:
    image: postgres:18
    container_name: nestjs_first_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: manhhuy
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: db_nestjs_postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-nestjs-first-postgres
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123123
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
